version: '3.8'

services:
  app:
    image: php:8.0-fpm
    container_name: laravel-app
    build:
      context: ./docker/php
    volumes:
      - ./src:/var/www/html
    networks:
      - laravel-network

  mysql:
    image: mysql:5.7
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: laravel
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - db_data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge

volumes:
  db_data: