services:
  db:
    image: mysql:lts
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
  app:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    image: laravel-app
    container_name: laravel-app
    ports:
      - "8000:8000"
    volumes:
      - ./src:/var/www
    depends_on:
      - db
    command: >
      bash -c "cd demo-app
      && php artisan serve --host=0.0.0.0"
volumes:
  db_data: